layout_spectrum: 0.5480607
color:
  saturation: 0.5023232
  lightness: 0.1449492
  brandStrength: 0.120961
  rhythmicContrast: 0.9346105
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.3007623
name: Adj Brown
